### ISSUE TITLE
Delete irrelevant requriements files

### ISSUE THREAD

**Issue by bedangSen** [Vi45en/Pesidious#2]

**Comment by bedangSen** [comment]
Consider moving the `requirements.txt` file to the root folder from the pip_requirements directory

**Comment by uuA1202** [comment]
Hello, the test data in the project cannot be downloaded.
I would appreciate it if you could send me an email or take other measures.
My email address:1656326360@qq.com

**Comment by vietvo89** [comment]
Hello BedangSen

I cannot find your requirements.txt in the root folder but found various requirement files in the pip_requirements directory. So what should be used?

Thanks

**Comment by vietvo89** [comment]
Hi BedangSen

I encountered various errors. It seems that some packages are old and not compatible with each other. 

Collecting numpy>=1.16.0 (from -r requirements_malgan.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d2/48/f445be426ccd9b2fb64155ac6730c7212358882e589cd3717477d739d9ff/numpy-1.20.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_ojzwz6d/numpy/setup.py", line 30, in <module>
        raise RuntimeError("Python version >= 3.7 required.")
    **RuntimeError: Python version >= 3.7 required.**
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_ojzwz6d/numpy/**

Collecting lief==0.10.0.dev0 (from -r requirements_rl.txt (line 12))
  **Could not find a version that satisfies the requirement lief==0.10.0.dev0** (from -r requirements_rl.txt (line 12)) (from versions: 0.8.0.post7, 0.8.1.post1, 0.8.2.post1, 0.8.3.post3, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4)
No matching distribution found for lief==0.10.0.dev0 (from -r requirements_rl.txt (line 12))

Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 3))
  **Could not find a version that satisfies the requirement pkg-resources==0.0.0** (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 3))
